# Generated by Django 3.2.15 on 2024-05-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodcartapp', '0048_auto_20240520_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес заказа')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Расстояние',
                'verbose_name_plural': 'Расстояния',
                'ordering': ['distance'],
                'unique_together': {('restaurant', 'order_address')},
            },
        ),
    ]
