# Generated by Django 3.2.15 on 2024-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='order_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Адрес заказа'),
        ),
    ]
