# Generated by Django 3.2.15 on 2024-05-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='client_lastname',
        ),
    ]
