# Generated by Django 3.2.15 on 2024-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Accepted'), ('Готовится', 'Cooking'), ('В пути', 'Delivering'), ('Доставлен', 'Delivered')], db_index=True, default='Принят', max_length=10),
        ),
    ]
